[tool.poetry]
name = "ollama-pdf-bot"
version = "0.1.0"
description = ""
authors = ["Ahmad Dwi <ahmad.dwi@rga.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
